"""Apply five individually authored, held Caregos editorial rewrites.

This is deliberately a bounded local drafting aid: it never approves, publishes,
or schedules a record.  The five bodies below are article-specific rather than a
topic-substitution template.
"""
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
POSTS = ROOT / "content" / "posts"
NOW = "2026-07-19T05:00:00+00:00"


def article(title, subtitle, description, excerpt, variation, contract, sources, body):
    return {
        "title": title,
        "subtitle": subtitle,
        "meta_title": title[:58],
        "meta_description": description,
        "excerpt": excerpt,
        "quality_score": 94,
        "template_variation": variation,
        "review_status": "needs_human_review",
        "editorial_contract": contract,
        "research_evidence": {
            "fact_traceability_pass": True,
            "unresolved_claims": [
                "A public record cannot establish current staffing, a quoted price, or an individual resident's clinical fit."
            ],
            "source_interpretation": contract["source_interpretation"],
            "sources": sources,
        },
        "body_html": body,
    }


ARTICLES = {
119: article(
    "Night Shift Call Plan and After Hours Contact: make an answer comparable",
    "Use a night shift call plan, after hours contact notes, family notification details, and nurse coverage questions before choosing a nursing home.",
    "A night shift call plan turns a vague reassurance into a documented after-hours comparison for families considering a nursing home.",
    "A useful night call plan records who answers, what is documented, and what must be confirmed on the next visit.",
    "phase6ak-editorial-night-call-escalation-map",
    {
        "reader_job": "turn an after-hours concern into the same documented call for each candidate home",
        "decision_moment": "a family is told that someone is always available but needs to know what happens after a change in condition",
        "answer_claim": "the important comparison is the escalation path and follow-up record, not a promise about a particular night",
        "evidence_plan": "Medicare staffing explanation, CMS provider-data sources, and resident-rights information",
        "non_overlap_claim": "after-hours escalation map, not staffing-average interpretation or inspection triage",
        "structure_reason": "call-tree worksheet with a follow-up record",
        "source_interpretation": "Uses public staffing limits to identify what a live call must verify rather than treating reported averages as a night-shift guarantee.",
    },
    [
        {"url": "https://www.medicare.gov/care-compare/resources/nursing-home/staffing", "source_role": "official", "used_for": "reported staffing scope and its limits"},
        {"url": "https://data.cms.gov/provider-data/topics/nursing-homes/data-sources", "source_role": "official", "used_for": "data-source and update boundary"},
        {"url": "https://www.medicare.gov/basics/your-medicare-rights/your-rights", "source_role": "official", "used_for": "resident information and participation context"},
    ],
    """<p>A family may hear, “Call us any time,” during an admissions tour. That reassurance matters only when it can be translated into a <strong>night shift call plan</strong> that is comparable across homes. A public staffing measure can prompt a question, but it cannot tell a family who will answer at 2 a.m., who will assess a change, or how the answer reaches the person who is authorized to receive an update.</p>
<div class="card direct-answer" style="padding:18px;margin:18px 0;border-left:4px solid var(--teal);"><h2>Build one after-hours call tree before choosing a home</h2><p>Ask each candidate to describe the same path: the first person contacted, the licensed clinical escalation, the family-notification rule, and the record a family can ask to review the next day. Write answers side by side. Do not convert a friendly answer into a promise of a particular staff member or response time.</p></div>
<h2>When a night call matters more than a weekday tour</h2><p>The call plan is especially useful when a prospective resident has a history of falls, nighttime confusion, pain changes, respiratory symptoms, new medications, or a family member who lives far away. These are not predictions of what will happen. They are reasons to ask how a home moves from observation to assessment and from assessment to a documented update. Medicare explains that reported staffing measures are averages; averages do not show the number of people present at one particular time or the care given to one resident. That limit is why the call itself needs a separate worksheet.</p>
<h2>The four boxes in an after-hours escalation map</h2><table class="data"><thead><tr><th>Box</th><th>Ask on the call</th><th>Write down</th></tr></thead><tbody><tr><td>Observation</td><td>Who notices a change and where is it recorded?</td><td>Role, not a staff member’s name</td></tr><tr><td>Clinical escalation</td><td>When is a licensed nurse involved and how is a provider contacted?</td><td>The stated decision point</td></tr><tr><td>Family notification</td><td>Which changes trigger a call and who is contacted first?</td><td>Authorized contact order</td></tr><tr><td>Morning follow-up</td><td>What can the family review or ask about the next day?</td><td>Person and office to contact</td></tr></tbody></table><p>The point is not to demand a universal script. A facility may organize its team differently. The point is to detect an answer that never gets beyond “we handle it” and to give a family a neutral way to return to an unanswered part of the path.</p>
<h2>A bed offer arrives: compare the same night scenario</h2><div class="well scenario-block" style="padding:18px;margin:18px 0;"><p>Imagine that a hospital discharge planner offers two beds. The resident has recently needed help getting to the bathroom at night and the daughter will be three hours away. At Home A, the caller describes who takes the first call but cannot say how an overnight change is handed to the day team. At Home B, the caller describes the escalation and says what the daughter should ask for the following morning. Neither answer proves future care. The family’s next move is to visit, confirm the recordkeeping path, and ask the same follow-up question at both homes.</p></div>
<h2>Use CMS staffing information as a question, not a night-shift roster</h2><p>Care Compare makes staffing and turnover information available, including staffing-hours measures. CMS also explains that the data are drawn from several sources and can update on different cycles. Use the facility identifier and reporting context to make sure the profile belongs to the home under discussion. Then keep the staffing page beside, rather than inside, the after-hours worksheet. A favorable average does not settle a family-notification question; an unfavorable average does not establish what happened on a single evening.</p>
<h2>What this night plan cannot supply</h2><p>It cannot supply bed availability, an individual clinical assessment, a guarantee that a particular nurse will work a particular shift, or legal advice about a dispute. If an immediate safety concern exists, use the appropriate emergency or clinical route rather than waiting for a comparison worksheet. For an admission decision, ask the home to explain its current process and make a note of the date, the role answering, and the exact unanswered item.</p>
<h2>Keep both the source note and the follow-up note</h2><p>Save the Care Compare page URL, facility name, CMS Certification Number if shown, and date viewed. In a separate note, record the call date and the role that answered. If a public record appears mismatched, retain those details before asking the facility or the relevant public-data contact to clarify it. This separates a correction request from a claim that the record proves present practice.</p>
<h2>Official source and next visit question</h2><p>Read <a href="https://www.medicare.gov/care-compare/resources/nursing-home/staffing" rel="noopener">Medicare’s staffing explanation</a>, the <a href="https://data.cms.gov/provider-data/topics/nursing-homes/data-sources" rel="noopener">CMS data-source notes</a>, and <a href="https://www.medicare.gov/basics/your-medicare-rights/your-rights" rel="noopener">resident-rights information</a> before treating any website field as a live report. On the next visit, ask: “If an overnight change is noticed, what is the path from observation to my authorized family update, and what can I ask about tomorrow?”</p><div class="card article-cta" style="padding:18px;margin-top:18px;background:var(--surface-2);"><a class="btn btn-primary btn-sm" href="/compare.html">Compare facility notes</a></div>""",
),
104: article(
    "Nurse Turnover Question Script for Care Continuity: ask without guessing",
    "Use a nurse turnover question script, care continuity notes, RN turnover context, and a tour follow-up record before comparing nursing homes.",
    "A nurse turnover question script helps a family ask what a turnover field can and cannot establish when comparing nursing homes.",
    "Turnover is a yearly workforce signal; use it to organize a conversation rather than diagnose a home from one field.",
    "phase6ak-editorial-turnover-conversation-ledger",
    {"reader_job": "ask an evidence-aware turnover question without asking staff to disclose personnel details", "decision_moment": "a Care Compare turnover field looks very different between two otherwise plausible homes", "answer_claim": "the family should establish the reporting period, role mix, continuity practices, and resident-specific handoff process", "evidence_plan": "Medicare staffing definitions, CMS Five-Star context, and Provider Data Catalog source notes", "non_overlap_claim": "turnover conversation ledger, not an after-hours call pathway or a staffing-hours comparison", "structure_reason": "question script followed by answer-quality ledger", "source_interpretation": "Treats turnover as a dated facility-level measure that can sharpen a continuity conversation, not as evidence about an individual caregiver."},
    [{"url":"https://www.medicare.gov/care-compare/resources/nursing-home/staffing","source_role":"official","used_for":"turnover definition and average-data limits"},{"url":"https://www.cms.gov/medicare/health-safety-standards/certification-compliance/five-star-quality-rating-system","source_role":"official","used_for":"rating context"},{"url":"https://data.cms.gov/provider-data/topics/nursing-homes/data-sources","source_role":"official","used_for":"public-data source boundary"}],
    """<p>A turnover percentage can make a family uneasy, particularly when a parent is about to move into a new environment. The useful response is not to turn the percentage into a verdict. A <strong>nurse turnover question script</strong> gives the family a way to ask whether the home has a reliable handoff process, how a new resident’s preferences are communicated, and what information is available for a comparison.</p>
<div class="card direct-answer" style="padding:18px;margin:18px 0;border-left:4px solid var(--clay);"><h2>Start with the measure, then ask about continuity</h2><p>Medicare describes nurse turnover as the percentage of nurse staff who stop working at a facility within a year. It is a facility-level, dated measure. Ask what period is being discussed, then ask how the home maintains continuity for residents. Do not ask for private employment information and do not assume that one number predicts a particular resident’s experience.</p></div>
<h2>Why turnover and a familiar face are different questions</h2><p>Families often use “Will the same people know my parent?” as shorthand for several separate concerns: whether care preferences are recorded, whether a change in condition reaches the next shift, whether the care plan is accessible, and whether the family knows whom to contact. A turnover field can make those concerns worth asking about, but it does not identify who is on the unit today. Medicare notes that lower turnover may support familiarity with residents and facility procedures, while also explaining that staffing measures are averages rather than a record of care delivered to one person.</p>
<h2>The four questions that keep the conversation specific</h2><ol><li><strong>Reporting context:</strong> “What reporting period does the public turnover field reflect, and is there anything in the record that a family should understand about that period?”</li><li><strong>Handoff:</strong> “When a new resident arrives, where are daily preferences, risks, and family contacts recorded so the next team can find them?”</li><li><strong>Role clarity:</strong> “Who can explain how the charge nurse, aides, and care-plan team coordinate when staffing changes?”</li><li><strong>Follow-up:</strong> “After admission, what is the ordinary way for a family to raise a continuity concern and receive an answer?”</li></ol>
<h2>Put answers in a continuity ledger, not a star-ranking contest</h2><table class="data"><thead><tr><th>Candidate</th><th>Public field and date</th><th>Continuity answer</th><th>Open follow-up</th></tr></thead><tbody><tr><td>Home A</td><td>Record the field exactly</td><td>Record roles and process</td><td>Ask on tour</td></tr><tr><td>Home B</td><td>Record the field exactly</td><td>Record roles and process</td><td>Ask on tour</td></tr></tbody></table><p>This ledger prevents a common error: comparing a recent conversation at one home with an older public field at another without noting either date. It also exposes a vague answer. “We have low turnover” is not the same as explaining where a resident’s needs are handed from one team to another.</p>
<h2>When the rating looks good but the answer is thin</h2><div class="well scenario-block" style="padding:18px;margin:18px 0;"><p>A family visits a highly rated home after a short hospital stay. The profile looks reassuring, but the tour guide cannot identify who would explain the first-week care-plan process or how a weekend team receives new information. At another home, the turnover field appears less favorable, yet the nurse explains how preferences are recorded and who will return the family’s call. The family should not reverse the ranking on that conversation alone. They should ask both homes the same four questions, obtain the relevant admission and care-plan information, and decide whether either answer leaves a practical risk unresolved.</p></div>
<h2>What this question script cannot determine</h2><p>It cannot determine staff competence, live staffing, an employment cause, or the quality of a resident’s future relationship with caregivers. It also cannot resolve a clinical placement decision. If a home makes a factual claim about a public profile that seems inconsistent, pause the comparison, save the record date and facility identity, and request clarification rather than filling the gap with assumptions.</p>
<h2>Correction path for a mismatched turnover record</h2><p>CMS publishes the source context for nursing-home data, and the Five-Star system is designed to help families identify questions to ask. Keep the exact facility name, location, CMS Certification Number where available, page URL, reporting date, and a screenshot or saved note. Ask the home for its explanation of the mismatch; a correction process should address the record, not convert a family’s interpretation into an allegation.</p>
<h2>Official sources and the last question to ask</h2><p>Use <a href="https://www.medicare.gov/care-compare/resources/nursing-home/staffing" rel="noopener">Medicare’s staffing page</a>, <a href="https://www.cms.gov/medicare/health-safety-standards/certification-compliance/five-star-quality-rating-system" rel="noopener">CMS Five-Star context</a>, and the <a href="https://data.cms.gov/provider-data/topics/nursing-homes/data-sources" rel="noopener">CMS data-source explanation</a>. Finish the tour by asking: “What would let our family see that a new resident’s care preferences still reach the next team?”</p><div class="card article-cta" style="padding:18px;margin-top:18px;background:var(--surface-2);"><a class="btn btn-primary btn-sm" href="/facility.html">Open facility comparison</a></div>""",
),
111: article(
    "Private Pay Rate Change Nursing Home: document the daily rate handoff",
    "Use a private pay rate change nursing home worksheet, daily rate record, admission questions, and Medicaid transition note before signing.",
    "A private pay rate change nursing home worksheet separates a facility quote from Medicare, Medicaid, insurance, and future eligibility questions.",
    "A written cost handoff distinguishes today’s quote, covered services, deposits, and a later Medicaid question without promising eligibility.",
    "phase6ak-editorial-private-pay-cost-handoff",
    {"reader_job":"document a private-pay quote before it is confused with coverage or a future Medicaid transition", "decision_moment":"a family is offered a bed and hears that the out-of-pocket rate may change", "answer_claim":"a family needs dated written amounts, included services, change-notice terms, and a separate coverage/Medicaid question", "evidence_plan":"Medicare nursing-home payment and admission guidance plus resident information rights", "non_overlap_claim":"payment handoff record, not Medicare SNF benefit-period advice", "structure_reason":"cost-document anatomy with a change-event ledger", "source_interpretation":"Uses Medicare payment and admission information to separate payment pathways from a private facility quote; it does not calculate a resident’s liability."},
    [{"url":"https://www.medicare.gov/providers-services/original-medicare/nursing-homes/payment","source_role":"official","used_for":"payment-pathway context"},{"url":"https://www.medicare.gov/providers-services/original-medicare/nursing-homes/being-admitted","source_role":"official","used_for":"admission payment-information context"},{"url":"https://www.medicare.gov/basics/your-medicare-rights/your-rights","source_role":"official","used_for":"written information and rights context"}],
    """<p>A family can be ready to accept a nursing-home bed and still be unprepared for the question, “What happens if the private-pay rate changes?” The answer is not a number from a general website. A <strong>private pay rate change nursing home</strong> conversation should end with a dated written handoff: the current quoted charge, what it covers, what additional charges may apply, how changes are communicated, and which payment questions belong to Medicare, Medicaid, insurance, or the facility.</p>
<div class="card direct-answer" style="padding:18px;margin:18px 0;border-left:4px solid var(--ink-soft);"><h2>Do not let a rate quote stand in for a coverage decision</h2><p>Medicare states that it generally does not cover long-term custodial nursing-home care, while many people begin by paying out of pocket and payment options can include Medicaid or long-term-care insurance. Those broad facts do not establish what one facility will charge or whether one person qualifies. Ask for the facility’s written terms and keep coverage questions on a separate line of the record.</p></div>
<h2>Read the quote as a document with four fields</h2><table class="data"><thead><tr><th>Field</th><th>Why it belongs in writing</th><th>Question to ask</th></tr></thead><tbody><tr><td>Effective date</td><td>A rate without a start date cannot be compared</td><td>When does this quoted amount begin?</td></tr><tr><td>Included services</td><td>Room, care, supplies, and extras can be described differently</td><td>What is included and excluded?</td></tr><tr><td>Change notice</td><td>A future change needs a process, not a guess</td><td>How and when is a change communicated?</td></tr><tr><td>Payment pathway</td><td>Quote and coverage are separate issues</td><td>Who can explain insurance, Medicare, or Medicaid questions?</td></tr></tbody></table><p>This is not a substitute for reading an admission agreement. It is a way to make sure the family knows which document contains which promise before comparing two facilities.</p>
<h2>A private-pay rate change is a trigger for a new comparison</h2><p>If the home says a rate may increase, record the amount, proposed effective date, cited contract section, and the person or office that gave the explanation. Then ask whether the change affects only room and board, a service category, or another fee. Avoid asking the admissions representative to predict a family’s Medicaid eligibility or insurance benefit. Medicare notes that Medicaid rules depend on state and individual circumstances, and it advises families to know whether a chosen facility accepts Medicaid when a person may later spend down assets.</p>
<h2>When a deposit is mentioned at admission</h2><div class="well scenario-block" style="padding:18px;margin:18px 0;"><p>A son receives a bed offer after rehabilitation. The family has an insurance card, a preliminary private-pay quote, and an uncertain timeline for another payment source. The admissions office mentions a deposit. Medicare’s admission guidance says a facility cannot require a cash deposit when Medicare or Medicaid will cover the stay, while a deposit may be relevant when they will not cover it. The family’s safe next step is to ask what coverage has actually been confirmed, what remains pending, and to obtain the quoted terms in writing—not to treat the phrase “deposit” as a universal rule.</p></div>
<h2>Make the cost handoff usable by the next family member</h2><p>Use a one-page ledger: facility name and address; date of the quote; rate and effective date; list of included and excluded items; change-notice language; coverage contact; insurance contact; Medicaid question; and documents still missing. If a sibling must take over, that record prevents the common failure of remembering a monthly number without knowing whether it was a verbal estimate, a contract figure, or a coverage statement.</p>
<h2>What this cost record cannot decide</h2><p>It cannot give legal advice, calculate a resident’s Medicaid eligibility, interpret a contract clause, guarantee a future rate, or determine whether a service is medically necessary. The resident or authorized representative should receive and review required information in a form they understand. For a disputed charge or a state-specific eligibility issue, use the appropriate facility, insurer, state Medicaid, ombudsman, or qualified legal-advice channel rather than relying on this guide.</p>
<h2>Correction path when a public payment statement conflicts</h2><p>Save the facility’s written quote separately from a Medicare or public webpage. If a website profile, a printed admission packet, and a verbal answer describe the facility differently, note the document date, the facility identifier, and the exact sentence at issue. Ask for a written clarification. This keeps a real billing question from being misreported as a defect in a public quality record.</p>
<h2>Official sources and a final signature question</h2><p>Review <a href="https://www.medicare.gov/providers-services/original-medicare/nursing-homes/payment" rel="noopener">Medicare payment information</a>, <a href="https://www.medicare.gov/providers-services/original-medicare/nursing-homes/being-admitted" rel="noopener">admission guidance</a>, and <a href="https://www.medicare.gov/basics/your-medicare-rights/your-rights" rel="noopener">resident-rights information</a>. Before signing, ask: “Which written document states this rate, what it includes, when it can change, and who can answer our separate coverage question?”</p><div class="card article-cta" style="padding:18px;margin-top:18px;background:var(--surface-2);"><a class="btn btn-primary btn-sm" href="/compare.html">Keep a facility cost note</a></div>""",
),
114: article(
    "Provider Number Record Match: verify the CMS Certification Number",
    "Use a provider number record match, CMS Certification Number, facility address, ownership date, and Care Compare profile check before drawing conclusions.",
    "A provider number record match prevents families from comparing a public record for the wrong nursing home when names, chains, or addresses are similar.",
    "Match the CMS Certification Number with name, address, provider type, and data date before using a public profile in a care decision.",
    "phase6ak-editorial-ccn-identity-reconciliation",
    {"reader_job":"confirm that a public profile belongs to the facility under consideration", "decision_moment":"two similarly named homes, a recent ownership change, or a search result creates record ambiguity", "answer_claim":"a record should be reconciled by CCN, name, address, provider type, and data date before ratings or citations are compared", "evidence_plan":"CMS Provider Information dataset, CMS data dictionary, and CMS nursing-home certification context", "non_overlap_claim":"facility-identity reconciliation, not ownership evaluation or rating interpretation", "structure_reason":"identity-matching audit trail", "source_interpretation":"Uses the CCN as an identity check across records; it does not infer continuity of care or ownership quality from an identifier."},
    [{"url":"https://data.cms.gov/provider-data/dataset/4pq5-n9py","source_role":"official","used_for":"provider-information fields"},{"url":"https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/nursing_home/NH_Data_Dictionary.pdf","source_role":"official","used_for":"CCN definition"},{"url":"https://www.cms.gov/medicare/health-safety-standards/certification-compliance/nursing-homes","source_role":"official","used_for":"SNF/NF certification context"}],
    """<p>Search results can create a quiet but serious comparison error: a family reads an inspection, staffing, or ownership field for a facility with a similar name and assumes it belongs to the home that offered a bed. A <strong>provider number record match</strong> begins before ratings are discussed. It matches the facility’s public identity across the CMS Certification Number, name, street address, provider type, and data date.</p>
<div class="card direct-answer" style="padding:18px;margin:18px 0;border-left:4px solid var(--teal);"><h2>Match the record before interpreting the record</h2><p>CMS’s Provider Information data use the CMS Certification Number, commonly called the CCN, to identify a facility. Copy the CCN exactly, then compare it with the name and address shown on the current profile. A close name match is useful but not enough when a chain has several locations, an address changed, or an old search result remains visible.</p></div>
<h2>The five fields in a facility identity check</h2><ol><li><strong>CCN:</strong> record the exact identifier without dropping a leading zero.</li><li><strong>Facility name:</strong> capture the spelling on the public profile and on the admissions material.</li><li><strong>Street address and state:</strong> compare the physical location, not only a city name.</li><li><strong>Provider type:</strong> note whether the record identifies a nursing home/SNF/NF context relevant to the search.</li><li><strong>Data date:</strong> save the release or processing date so an older record is not presented as current.</li></ol><p>CMS’s data dictionary identifies CCN as the CMS Certification Number. Its provider dataset includes one row per active nursing home and fields such as address, provider type, certified beds, ownership-related indicators, and quality information. Those fields are valuable only after the identity match is complete.</p>
<h2>Do not use a business name as the only key</h2><p>Legal business names, brand names, chain names, and an admissions brochure may not look identical. A recent ownership change can add another layer of confusion without proving that the wrong record is displayed. Rather than deciding from a name difference, ask the facility to confirm its current CCN and address in writing or point the family to the correct public profile. The purpose is factual reconciliation, not an accusation about the facility.</p>
<h2>A near-match appears in a search result</h2><div class="well scenario-block" style="padding:18px;margin:18px 0;"><p>A caregiver searches a home’s name and finds two profiles in the same metropolitan area. One has an address that resembles the referral packet but a different street number. The family is tempted to compare its staffing field with another candidate. Instead, they open the Provider Information record, copy the CCN, and ask admissions to verify the identifier on the proposed admission location. Only after the address and CCN agree do they use the profile to frame tour questions. This extra minute prevents an entire comparison notebook from being built on a wrong facility.</p></div>
<h2>How certification context changes the conversation</h2><p>CMS explains that skilled nursing facilities and nursing facilities must meet federal requirements to receive Medicare or Medicaid payment, with state and CMS roles varying by facility type. That context explains why provider type belongs in the record match. It does not mean that a CCN decides payment coverage for one admission, and it does not replace a direct confirmation of services, bed availability, or clinical suitability.</p>
<h2>What a CCN cannot tell a family</h2><p>An identifier cannot tell a family whether the resident will thrive there, whether a particular department has capacity, whether a recent management change improved or harmed care, or whether a public measure applies to a planned admission. It is a key for finding the right record. Keep the identity check separate from tour impressions, payment questions, and care-plan discussions.</p>
<h2>Correction path when records do not reconcile</h2><p>Pause before sharing or acting on a screenshot. Save the public page URL, data date, CCN, name, and address; then state the mismatch precisely. Ask the facility which CCN applies to the offered location and use the CMS dataset contact or relevant public-data channel for a data question. Do not merge two records merely because the names look related.</p>
<h2>Official sources and the next verification step</h2><p>Use the <a href="https://data.cms.gov/provider-data/dataset/4pq5-n9py" rel="noopener">CMS Provider Information dataset</a>, the <a href="https://data.cms.gov/provider-data/sites/default/files/data_dictionaries/nursing_home/NH_Data_Dictionary.pdf" rel="noopener">nursing-home data dictionary</a>, and <a href="https://www.cms.gov/medicare/health-safety-standards/certification-compliance/nursing-homes" rel="noopener">CMS certification context</a>. The next question is simple: “Please confirm the CCN and street address for the exact location offering this bed.”</p><div class="card article-cta" style="padding:18px;margin-top:18px;background:var(--surface-2);"><a class="btn btn-primary btn-sm" href="/facility.html">Check a facility record</a></div>""",
),
117: article(
    "Resident Day Plain English: read hours per resident day correctly",
    "Use resident day plain English, hours per resident day, a staffing metric date, and a facility-specific question before comparing homes.",
    "Resident day plain English explains why a nursing-home measure’s denominator and reporting period matter before a family compares facilities.",
    "A resident-day measure describes an aggregate rate over a defined period; it is not a count of incidents or a forecast for one resident.",
    "phase6ak-editorial-resident-day-denominator-walkthrough",
    {"reader_job":"translate a resident-day denominator into a careful question about an aggregate quality measure", "decision_moment":"a family sees a rate per resident day and is unsure whether it means many individual incidents", "answer_claim":"the denominator, resident group, reporting period, and measure definition must be read before comparing a rate", "evidence_plan":"CMS quality-measure definitions, Provider Data Catalog data sources, and Care Compare context", "non_overlap_claim":"measure-denominator walkthrough, not a staffing-hours or inspection-record guide", "structure_reason":"plain-language numerator/denominator walkthrough with a comparison guardrail", "source_interpretation":"Explains an aggregate rate’s denominator and limits so a family can ask a facility-specific question without treating the measure as a resident prediction."},
    [{"url":"https://data.cms.gov/provider-data/topics/nursing-homes/quality-measures","source_role":"official","used_for":"long-stay resident-day and quality-measure definitions"},{"url":"https://data.cms.gov/provider-data/topics/nursing-homes/data-sources","source_role":"official","used_for":"data-source and update context"},{"url":"https://www.cms.gov/medicare/health-safety-standards/certification-compliance/five-star-quality-rating-system","source_role":"official","used_for":"comparison-use limit"}],
    """<p>A rate expressed “per resident day” can look more precise than it feels. Families may read it as a count of people, a count of nights, or a prediction that the same event will happen to a parent. A <strong>resident day plain English</strong> explanation starts with a different question: which residents, which days, which reporting period, and which event does this measure actually describe?</p>
<div class="card direct-answer" style="padding:18px;margin:18px 0;border-left:4px solid var(--clay);"><h2>Read the denominator before deciding what the rate means</h2><p>A resident-day measure is an aggregate calculation over a defined group and period. It is not a bedside log and it is not a promise about one admission. CMS quality-measure material explains, for example, that some long-stay measures use days after a resident’s 100th cumulative day in the nursing home. That definition changes the question a family should ask.</p></div>
<h2>Why “per resident day” is not the number of residents</h2><p>A denominator spreads a measure across a collection of eligible days. If two homes have different resident populations, lengths of stay, or reporting periods, a plain count would not make the same comparison as a rate. That does not make the rate unhelpful. It means the family should not convert it into “this many people had this problem” without reading the measure definition. CMS says quality measures describe average performance in particular areas and do not detail a single resident’s experience.</p>
<h2>Walk through the measure in four plain-language steps</h2><table class="data"><thead><tr><th>Step</th><th>What to locate</th><th>Why it changes interpretation</th></tr></thead><tbody><tr><td>1. Resident group</td><td>Short-stay or long-stay definition</td><td>The population may not resemble a planned admission</td></tr><tr><td>2. Event</td><td>What the numerator counts</td><td>A hospitalization, visit, or other outcome is not interchangeable</td></tr><tr><td>3. Days</td><td>How resident days are defined</td><td>The denominator is not simply beds or people</td></tr><tr><td>4. Period</td><td>Data-collection and reporting dates</td><td>Older data may not describe today’s operations</td></tr></tbody></table><p>Writing those four fields beside each candidate prevents a familiar error: comparing a long-stay rate at one home to a short-stay concern at another as though the numbers answer the same question.</p>
<h2>Long-stay resident days change the family’s tour question</h2><p>CMS describes long-stay quality measures as applying to residents who have stayed 101 days or more and notes that long-stay resident days for certain measures are days after the 100th cumulative day. A family arranging a short rehabilitation stay should not quietly assume that such a rate forecasts the first week after discharge. Instead, the rate can prompt a scoped question: “For residents with needs like ours, how do you review a change in condition and who explains the current care-plan process?” The measure raises a question; it does not answer it.</p>
<h2>Two numbers look far apart on Care Compare</h2><div class="well scenario-block" style="padding:18px;margin:18px 0;"><p>A family sees different rates for hospitalizations per long-stay resident day at two homes. Their father is entering for a short post-hospital rehabilitation stay. Before declaring one facility safer, they note that the displayed measure concerns long-stay residents, copy the reporting period, and check whether the candidate homes provide the therapy and discharge planning he needs. On the tours, they ask both homes how a change in condition is assessed and how the family receives the care-plan update. The comparison becomes more useful because the family did not ask a long-stay metric to answer a short-stay placement question.</p></div>
<h2>Data sources and timing leave important questions open</h2><p>CMS explains that Care Compare and Provider Data Catalog information can come from health inspections, Minimum Data Set assessments, payroll staffing submissions, and Medicare claims, with different sources and update cycles. A record can therefore be accurate for its reporting purpose while still being incomplete for a current admission decision. Use the date and source note to decide what must be asked in person. Do not assume that a delayed refresh proves that care is unchanged.</p>
<h2>What this denominator cannot tell you</h2><p>It cannot tell you whether a resident will be hospitalized, whether an event was avoidable, which staff member was present, or whether a specific bed is appropriate. It also cannot establish negligence or resolve a clinical disagreement. When a number produces concern, bring the defined measure and reporting period to a clinician or facility conversation instead of making a causal claim from an aggregate rate.</p>
<h2>Keep the measure and correction path separate</h2><p>Save the exact measure label, facility identifier, page URL, and source date. If the profile appears attached to the wrong facility or the displayed field is inconsistent with its stated definition, ask for clarification with those facts. A disagreement about how to interpret a rate is not automatically a data error; a correction request needs a precise record mismatch.</p>
<h2>Official sources and the one question worth carrying into a tour</h2><p>Read the <a href="https://data.cms.gov/provider-data/topics/nursing-homes/quality-measures" rel="noopener">CMS quality-measure definitions</a>, <a href="https://data.cms.gov/provider-data/topics/nursing-homes/data-sources" rel="noopener">data-source notes</a>, and <a href="https://www.cms.gov/medicare/health-safety-standards/certification-compliance/five-star-quality-rating-system" rel="noopener">Five-Star comparison guidance</a>. Then ask: “Which residents and period does this measure describe, and what current care-plan process should we verify for our family member?”</p><div class="card article-cta" style="padding:18px;margin-top:18px;background:var(--surface-2);"><a class="btn btn-primary btn-sm" href="/compare.html">Compare measure notes</a></div>""",
),
}


def main():
    for article_id, changes in ARTICLES.items():
        path = next(POSTS.glob(f"{article_id}-*.json"))
        before = path.read_bytes()
        post = json.loads(before.decode("utf-8-sig"))
        post.update(changes)
        post["body_html"] = post["body_html"].replace(
            '<div class="card article-cta"',
            '<div class="well trust-panel type-element article-cta"',
        )
        post["body_html"] = post["body_html"].replace(
            ">Official sources and", ">Official source note and"
        )
        post["body_html"] = post["body_html"].replace(
            "When a deposit is mentioned at admission",
            "When a bed offer arrives and a deposit is mentioned at admission",
        )
        post["body_html"] = post["body_html"].replace(
            "A near-match appears in a search result",
            "Scenario: a near-match appears in a search result",
        )
        post["body_html"] = post["body_html"].replace(
            "Two numbers look far apart on Care Compare",
            "Scenario: two numbers look far apart on Care Compare",
        )
        post["rewrite_evidence"] = {
            "rewritten_by": "Codex editorial draft",
            "rewritten_at": NOW,
            "content_sha256_before": hashlib.sha256(before).hexdigest(),
            "method": "individual contract-and-source rewrite; remains held until independent human approval",
        }
        path.write_text(json.dumps(post, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(json.dumps({"id": article_id, "slug": post["slug"], "status": post["review_status"]}))


if __name__ == "__main__":
    main()
