import argparse
import email.utils
import html
import json
import os
import shutil
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
POST_DIR = ROOT / "content" / "posts"
BLOG_DIR = ROOT / "blog"
GENERATED_MARKER = "<!-- generated by scripts/generate_blog.py -->"
CATEGORY_LABELS = {
    "ratings": "Ratings",
    "staffing": "Staffing",
    "inspections": "Inspections",
    "enforcement": "Enforcement",
    "payment": "Payment",
    "decision": "Care Decisions",
    "comparison": "Comparisons",
    "data": "Data Literacy",
    "glossary": "Glossary",
    "tour": "Tour Questions",
}


def parse_dt(value: str) -> datetime:
    value = value.replace("Z", "+00:00")
    dt = datetime.fromisoformat(value)
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def now_from_env(value: str | None) -> datetime:
    value = value or os.environ.get("SITE_NOW")
    return parse_dt(value) if value else datetime.now(timezone.utc).astimezone()


def read_posts() -> list[dict]:
    posts = []
    for path in sorted(POST_DIR.glob("*.json")):
        post = json.loads(path.read_text(encoding="utf-8-sig"))
        post["_path"] = str(path)
        post["_publish_dt"] = parse_dt(post["publish_at"])
        posts.append(post)
    return posts


def rel_rss(path_depth: int) -> str:
    return "../" * path_depth + "rss.xml"


def normalize_html_output(value: str) -> str:
    return (
        value.replace("\uca0c", "&middot;")
        .replace("\u0431\u0434", "&middot;")
        .replace("\u00b7", "&middot;")
        .replace("Scheduled ", "Published ")
    )


def clean_text(value: str) -> str:
    return html.unescape(re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", value))).strip()


def extract_faq(body: str) -> list[dict]:
    marker = re.search(r"<h2[^>]*>\s*Brief FAQ\s*</h2>(.*?)(?:<h2|$)", body, flags=re.I | re.S)
    if not marker:
        return []
    section = marker.group(1)
    matches = re.findall(r"<h3[^>]*>(.*?)</h3>\s*<p[^>]*>(.*?)</p>", section, flags=re.I | re.S)
    return [
        {
            "@type": "Question",
            "name": clean_text(question),
            "acceptedAnswer": {"@type": "Answer", "text": clean_text(answer)},
        }
        for question, answer in matches
        if clean_text(question) and clean_text(answer)
    ]


def page_head(post: dict, site_url: str) -> str:
    title = html.escape(post["meta_title"])
    desc = html.escape(post["meta_description"])
    canonical = html.escape(post["canonical"])
    category_name = CATEGORY_LABELS.get(post["category"], post["category"].title())
    graph = [
        {
            "@type": post.get("schema_type", "Article"),
            "headline": post["title"],
            "description": post["excerpt"],
            "datePublished": post["publish_at"],
            "dateModified": post["publish_at"],
            "author": {"@type": "Organization", "name": "Caregos Editorial Team"},
            "publisher": {"@type": "Organization", "name": "Caregos", "url": site_url.rstrip("/") + "/"},
            "mainEntityOfPage": canonical,
            "isBasedOn": post["external_source"]["url"],
            "articleSection": category_name,
            "keywords": [post["main_keyword"], *post["expanded_keywords"]],
        },
        {
            "@type": "BreadcrumbList",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": site_url.rstrip("/") + "/"},
                {"@type": "ListItem", "position": 2, "name": "Guides", "item": site_url.rstrip("/") + "/blog/"},
                {"@type": "ListItem", "position": 3, "name": category_name},
                {"@type": "ListItem", "position": 4, "name": post["title"], "item": canonical},
            ],
        },
    ]
    faq = extract_faq(post["body_html"])
    if faq:
        graph.append({"@type": "FAQPage", "mainEntity": faq})
    json_ld = {"@context": "https://schema.org", "@graph": graph}
    return f"""<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<meta name="google-adsense-account" content="ca-pub-3050601904412736">
<link rel="icon" href="../../favicon.svg" type="image/svg+xml">
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{canonical}">
<link rel="alternate" type="application/rss+xml" title="Caregos Blog RSS" href="../../rss.xml">
<link rel="stylesheet" href="../../styles/nh-data.css">
<script type="application/ld+json">{json.dumps(json_ld, ensure_ascii=False)}</script>"""


def nav(active_blog: bool = True) -> str:
    active = ' class="active"' if active_blog else ""
    return f"""<header class="topbar"><div class="wrap">
  <a class="brand" href="/">
    <svg class="mark" viewBox="0 0 26 26" fill="none"><rect width="26" height="26" rx="6" fill="#16323a"/><rect x="6" y="14" width="3.4" height="6" rx="1" fill="#b5623a"/><rect x="11.3" y="9" width="3.4" height="11" rx="1" fill="#e4efef"/><rect x="16.6" y="6" width="3.4" height="14" rx="1" fill="#2c7a7b"/></svg>
    Caregos
  </a>
  <nav class="nav">
    <a href="/listings.html">Find facilities</a>
    <a href="/compare.html">Compare</a>
    <a href="/enforcement.html">Enforcement</a>
    <a href="/blog/"{active}>Guides</a>
    <a href="/methodology.html">Methodology</a>
  </nav>
</div></header>"""


def slug_id(value: str) -> str:
    text = re.sub(r"<[^>]+>", "", value).lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return text or "section"


def add_heading_ids(body: str) -> tuple[str, list[tuple[str, str]]]:
    headings: list[tuple[str, str]] = []
    seen: dict[str, int] = {}

    def repl(match: re.Match[str]) -> str:
        attrs = match.group(1) or ""
        raw = match.group(2)
        clean = re.sub(r"<[^>]+>", "", raw)
        base = slug_id(clean)
        seen[base] = seen.get(base, 0) + 1
        hid = base if seen[base] == 1 else f"{base}-{seen[base]}"
        headings.append((hid, clean))
        if " id=" in attrs:
            return match.group(0)
        return f'<h2{attrs} id="{html.escape(hid)}">{raw}</h2>'

    return re.sub(r"<h2([^>]*)>(.*?)</h2>", repl, body), headings


def render_toc(headings: list[tuple[str, str]]) -> str:
    items = "".join(
        f'<li><a href="#{html.escape(hid)}">{html.escape(label)}</a></li>'
        for hid, label in headings[:12]
    )
    return f'<nav class="toc card" aria-label="Article table of contents"><b>Table of contents</b><ol>{items}</ol></nav>'


def related_posts(post: dict, published: list[dict], limit: int = 3) -> list[dict]:
    same_category = [
        candidate for candidate in published
        if candidate["slug"] != post["slug"] and candidate["category"] == post["category"]
    ]
    fallback = [
        candidate for candidate in published
        if candidate["slug"] != post["slug"] and candidate not in same_category
    ]
    return (same_category + fallback)[:limit]


def render_related(post: dict, published: list[dict]) -> str:
    items = related_posts(post, published)
    if not items:
        return ""
    cards = "".join(
        f"""<article class="related-card">
          <span>{html.escape(CATEGORY_LABELS.get(item["category"], item["category"].title()))}</span>
          <h3><a href="/blog/{html.escape(item["slug"])}/">{html.escape(item["title"])}</a></h3>
          <p>{html.escape(item["excerpt"])}</p>
        </article>"""
        for item in items
    )
    return f"""<section class="related-guides" aria-labelledby="related-guides">
        <h2 id="related-guides">Related guides to read next</h2>
        <div class="related-grid">{cards}</div>
      </section>"""


def render_related_rail(post: dict, published: list[dict]) -> str:
    items = related_posts(post, published, limit=3)
    if not items:
        return ""
    links = "".join(
        f'<li><a href="/blog/{html.escape(item["slug"])}/">{html.escape(item["title"])}</a></li>'
        for item in items
    )
    return f"""<div class="card related-rail">
        <h2 style="font-size:1.05rem;margin-bottom:8px;">Related guides</h2>
        <ul>{links}</ul>
      </div>"""


def footer() -> str:
    return normalize_html_output("""<footer class="foot"><div class="wrap">
  <div class="between" style="align-items:flex-start; flex-wrap:wrap; gap:32px;">
    <div style="max-width:340px;">
      <div class="brand" style="color:#fff; margin-bottom:10px;">Caregos</div>
      <p class="byline">An independent civic-data project. Ratings and enforcement records are published by CMS. Blog articles are editorial guides and do not replace medical, legal, or payment advice.</p>
    </div>
    <div class="row" style="gap:48px; flex-wrap:wrap;">
      <div class="stack" style="gap:8px;"><div class="foothead">Data</div>
        <a href="/methodology.html">Methodology</a><a href="/methodology.html#sources">Sources &amp; cadence</a><a href="/corrections.html">Corrections</a></div>
      <div class="stack" style="gap:8px;"><div class="foothead">Explore</div>
        <a href="/listings.html">Find facilities</a><a href="/compare.html">Compare</a><a href="/blog/">Guides</a></div>
      <div class="stack" style="gap:8px;"><div class="foothead">About</div>
        <a href="/about.html">About</a><a href="/privacy.html">Privacy</a></div>
    </div>
  </div>
  <hr style="border:0; border-top:1px solid #2c4d56; margin:28px 0 16px;">
  <p class="byline" style="margin:0;">Maintained by the Caregos editorial team · <a href="/corrections.html">Report a correction</a></p>
</div></footer>""")


def render_post(post: dict, site_url: str, published_posts: list[dict]) -> str:
    keyword = html.escape(post["main_keyword"])
    expanded = ", ".join(html.escape(k) for k in post["expanded_keywords"])
    body, headings = add_heading_ids(post["body_html"])
    toc = render_toc(headings) if headings else ""
    related = render_related(post, published_posts)
    related_rail = render_related_rail(post, published_posts)
    published_label = parse_dt(post["publish_at"]).strftime("%B %-d, %Y") if os.name != "nt" else parse_dt(post["publish_at"]).strftime("%B %#d, %Y")
    published = published_label
    return normalize_html_output(f"""<!DOCTYPE html>
<html lang="en">
<head>
{page_head(post, site_url)}
<style>
  .article-head {{ padding: 34px 0 18px; }}
  .crumbs {{ font-size:.84rem;color:var(--text-3);margin-bottom:12px; }}
  .article-meta {{ display:flex;gap:10px;flex-wrap:wrap;color:var(--text-3);font-size:.84rem;margin-top:14px; }}
  .article-layout {{ display:grid;grid-template-columns:minmax(0,1fr) 290px;gap:38px;align-items:start;padding-bottom:46px; }}
  @media (max-width: 920px){{ .article-layout {{ grid-template-columns:1fr; }} .rail {{ display:none; }} }}
  .art-body {{ font-size:1.02rem;line-height:1.72; }}
  .art-body h2 {{ margin:34px 0 10px;font-size:1.45rem; }}
  .art-body p, .art-body ul {{ max-width:72ch; }}
  .art-body li {{ margin:7px 0; }}
  .toc {{ padding:16px 18px;margin:20px 0; }}
  .toc ol {{ margin:8px 0 0;padding-left:20px; }}
  .toc a {{ color:var(--ink); text-decoration:none; }}
  .toc a:hover {{ text-decoration:underline; text-decoration-color:var(--clay); }}
  .rail {{ position:sticky;top:84px;display:grid;gap:16px; }}
  .rail .card {{ padding:18px; }}
  .related-guides {{ margin-top:38px;padding-top:24px;border-top:1px solid var(--line); }}
  .related-grid {{ display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:12px; }}
  .related-card {{ border:1px solid var(--line);border-radius:var(--r-lg);padding:16px;background:var(--surface); }}
  .related-card span {{ font-size:.68rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:var(--clay-dark); }}
  .related-card h3 {{ font-size:1.02rem;line-height:1.2;margin:6px 0 6px; }}
  .related-card h3 a {{ color:var(--ink);text-decoration:none; }}
  .related-card h3 a:hover {{ text-decoration:underline;text-decoration-color:var(--clay); }}
  .related-card p {{ font-size:.86rem;color:var(--text-2);margin:0;line-height:1.45; }}
  .related-rail ul {{ margin:0;padding-left:18px; }}
  .related-rail li {{ margin:8px 0;font-size:.88rem;line-height:1.35; }}
  .related-rail a {{ color:var(--ink);text-decoration:none; }}
  .related-rail a:hover {{ text-decoration:underline;text-decoration-color:var(--clay); }}
  @media (max-width:760px){{ .related-grid {{ grid-template-columns:1fr; }} }}
</style>
</head>
<body>
{GENERATED_MARKER}
<a class="skip" href="#main">Skip to content</a>
{nav()}
<main id="main" class="wrap">
  <div class="article-head">
    <div class="crumbs"><a href="/blog/">Blog</a> · {html.escape(CATEGORY_LABELS.get(post["category"], post["category"].title()))}</div>
    <h1>{html.escape(post["title"])}</h1>
    <p class="lede" style="margin-top:12px;">{html.escape(post["subtitle"])}</p>
    <div class="article-meta"><span>{html.escape(post["author"])}</span><span>·</span><span>{post["read_minutes"]} min read</span><span>·</span><span>Scheduled {published}</span></div>
  </div>
  <div class="article-layout">
    <article class="art-body">
      <p class="caption"><b>Main keyword:</b> {keyword} · <b>Expanded keywords:</b> {expanded}</p>
      {toc}
      {body}
      {related}
    </article>
    <aside class="rail">
      <div class="card">
        <h2 style="font-size:1.05rem;margin-bottom:8px;">Source note</h2>
        <p class="caption" style="margin-bottom:10px;">This guide cites an official source and should be read with the source date on any facility record.</p>
        <a class="caption" href="{html.escape(post["external_source"]["url"])}" rel="noopener">{html.escape(post["external_source"]["label"])}</a>
      </div>
      <div class="card">
        <h2 style="font-size:1.05rem;margin-bottom:8px;">Next step</h2>
        <p class="caption">Use the topic with a real facility profile before deciding.</p>
        <a class="btn btn-primary btn-sm" href="/listings.html">Find facilities</a>
      </div>
      {related_rail}
    </aside>
  </div>
</main>
{footer()}
<script src="../../styles/nh.js"></script>
</body>
</html>`n""")


def clean_generated(posts: list[dict]) -> None:
    for post in posts:
        target = BLOG_DIR / post["slug"]
        index = target / "index.html"
        if index.exists() and GENERATED_MARKER in index.read_text(encoding="utf-8", errors="ignore"):
            shutil.rmtree(target)


def render_index(posts: list[dict]) -> str:
    grouped: dict[str, list[dict]] = {}
    for post in posts:
        grouped.setdefault(post["category"], []).append(post)

    all_cards = "\n".join(
        f"""<article class="card gcard">
      <span class="cat">{html.escape(post['category'].title())}</span>
      <h2><a href="/blog/{html.escape(post['slug'])}/">{html.escape(post['title'])}</a></h2>
      <p>{html.escape(post['excerpt'])}</p>
      <div class="meta"><span>{html.escape(post['author'])}</span><span class="dot"></span><span>{post['read_minutes']} min read</span></div>
    </article>"""
        for post in posts
    )
    if not all_cards:
        all_cards = '<div class="card" style="padding:24px;color:var(--text-2);">Scheduled guides will appear here as they publish.</div>'

    hub_sections = []
    for category, label in CATEGORY_LABELS.items():
        items = grouped.get(category, [])[:4]
        if not items:
            continue
        links = "".join(
            f'<li><a href="/blog/{html.escape(post["slug"])}/">{html.escape(post["title"])}</a></li>'
            for post in items
        )
        hub_sections.append(
            f"""<section class="hub-section" aria-labelledby="hub-{html.escape(category)}">
      <h2 id="hub-{html.escape(category)}">{html.escape(label)}</h2>
      <ul>{links}</ul>
    </section>"""
        )
    hubs = "\n".join(hub_sections)
    item_list = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "Caregos Nursing Home Guides",
        "itemListElement": [
            {
                "@type": "ListItem",
                "position": index + 1,
                "url": f"https://caregos.com/blog/{post['slug']}/",
                "name": post["title"],
            }
            for index, post in enumerate(posts)
        ],
    }
    return normalize_html_output(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<meta name="google-adsense-account" content="ca-pub-3050601904412736">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<title>Nursing Home Data Blog · CMS Rating & Staffing Guides</title>
<meta name="description" content="Nursing home data blog with CMS rating guides, staffing explanations, inspection records, abuse flags, payment topics, and care decision resources.">
<link rel="canonical" href="https://caregos.com/blog/">
<link rel="alternate" type="application/rss+xml" title="Caregos Blog RSS" href="../rss.xml">
<link rel="stylesheet" href="../styles/nh-data.css">
<script type="application/ld+json">{json.dumps(item_list, ensure_ascii=False)}</script>
<style>
  .blog-head {{ padding: 36px 0 8px; }}
  .cats {{ display:flex;gap:8px;flex-wrap:wrap;margin:18px 0 8px; }}
  .hub-grid {{ display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin:24px 0 4px; }}
  .hub-section {{ border-top:1px solid var(--line);padding-top:14px; }}
  .hub-section h2 {{ font-size:1rem;margin-bottom:8px; }}
  .hub-section ul {{ margin:0;padding-left:18px;color:var(--text-2); }}
  .hub-section li {{ margin:6px 0; }}
  .hub-section a {{ color:var(--ink); text-decoration:none; }}
  .hub-section a:hover {{ text-decoration:underline; text-decoration-color:var(--clay); }}
  .glist {{ display:grid;grid-template-columns:1fr 1fr;gap:16px;padding:28px 0 48px; }}
  @media (max-width:760px){{ .glist, .hub-grid {{ grid-template-columns:1fr; }} }}
  .gcard {{ padding:22px;display:grid;gap:8px;align-content:start; }}
  .gcard .cat {{ font-size:.7rem;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:var(--clay-dark); }}
  .gcard h2 {{ font-size:1.24rem;line-height:1.16; }}
  .gcard h2 a {{ text-decoration:none;color:var(--ink); }}
  .gcard p {{ font-size:.9rem;color:var(--text-2);margin:0; }}
  .gcard .meta {{ font-size:.78rem;color:var(--text-3);display:flex;gap:10px;align-items:center;margin-top:2px; }}
  .meta .dot {{ width:3px;height:3px;border-radius:50%;background:var(--text-3); }}
</style>
</head>
<body>
<a class="skip" href="#main">Skip to content</a>
{nav()}
<main id="main" class="wrap">
  <div class="blog-head">
    <div class="eyebrow">Blog</div>
    <h1 style="margin:6px 0 8px;">Understand the data before you decide</h1>
    <p class="lede">Plain-language explainers on CMS ratings, staffing, inspection records, payment questions, and care decisions. New guides publish every five hours.</p>
    <div class="cats"><span class="chip on">All guides</span><span class="chip">Ratings</span><span class="chip">Staffing</span><span class="chip">Enforcement</span><span class="chip">Payment</span><span class="chip">Tours</span></div>
  </div>
  <div class="hub-grid" aria-label="Guide categories">
    {hubs}
  </div>
  <div class="glist">
    <article class="card gcard">
      <span class="cat">Ratings</span>
      <h2><a href="/blog/five-star-rating/">How to read a CMS five-star rating (and what it hides)</a></h2>
      <p>The overall star is an average of three very different things. Understand the domains before you compare.</p>
      <div class="meta"><span>Caregos Editorial Team</span><span class="dot"></span><span>8 min read</span></div>
    </article>
    {all_cards}
  </div>
</main>
{footer()}
<script src="../styles/nh.js"></script>
</body>
</html>`n""")


def render_rss(posts: list[dict], site_url: str, now: datetime) -> str:
    items = []
    for post in posts[:25]:
        link = urljoin(site_url.rstrip("/") + "/", f"blog/{post['slug']}/")
        pub = email.utils.format_datetime(parse_dt(post["publish_at"]))
        items.append(
            f"""    <item>
      <title>{html.escape(post['title'])}</title>
      <link>{link}</link>
      <guid isPermaLink="true">{link}</guid>
      <pubDate>{pub}</pubDate>
      <description>{html.escape(post['excerpt'])}</description>
    </item>"""
        )
    last = email.utils.format_datetime(now)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Caregos Blog</title>
    <link>{site_url.rstrip('/')}/blog/</link>
    <description>Nursing home CMS rating, staffing, inspection, payment, and enforcement guides from Caregos.</description>
    <language>en-us</language>
    <lastBuildDate>{last}</lastBuildDate>
    <atom:link href="{site_url.rstrip('/')}/rss.xml" rel="self" type="application/rss+xml" />
{chr(10).join(items)}
  </channel>
</rss>
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate scheduled blog pages for Caregos.")
    parser.add_argument("--site-url", default="https://caregos.com/")
    parser.add_argument("--now", default=None)
    args = parser.parse_args()
    now = now_from_env(args.now)
    all_posts = read_posts()
    clean_generated(all_posts)
    published = [p for p in all_posts if p["_publish_dt"] <= now]
    published.sort(key=lambda p: p["_publish_dt"], reverse=True)
    for post in published:
        target = BLOG_DIR / post["slug"]
        target.mkdir(parents=True, exist_ok=True)
        (target / "index.html").write_text(render_post(post, args.site_url, published), encoding="utf-8")
    (BLOG_DIR / "index.html").write_text(render_index(published), encoding="utf-8")
    (ROOT / "rss.xml").write_text(render_rss(published, args.site_url, now), encoding="utf-8")
    print(f"Generated {len(published)} published posts at {now.isoformat()}")


if __name__ == "__main__":
    main()
