"""Apply five independently authored, held Caregos editorial rewrites.

This is deliberately a finite evidence packet, not a prose template.  Each
entry has its own contract, sources, structure, and decision task.  It never
approves, publishes, or schedules a record.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POSTS = ROOT / "content" / "posts"


def source(url, used_for):
    return {"url": url, "source_role": "official", "used_for": used_for}


ARTICLES = {
116: {
 "title": "Dataset To Tour Question: provider data and facility tour guide",
 "subtitle": "Dataset to tour question for provider data, inspection record, and facility tour observations that a family can compare.",
 "excerpt": "Turn one public data field into a dated observation request, rather than treating the field as a bedside verdict.",
 "variation": "phase6ak-editorial-data-to-observation-card",
 "contract": {"reader_job":"convert one public field into an observable tour question","decision_moment":"a Care Compare or Provider Data field changes a shortlist","answer_claim":"a dataset field is most useful when it names what to observe, ask, and record on the visit","evidence_plan":"CMS Provider Data Catalog, Medicare Care Compare inspection context, Medicare visit guidance","non_overlap_claim":"data-to-observation card rather than an inspection chronology or rating explanation","structure_reason":"field-to-observation translation board with a two-home visit scenario"},
 "sources": [source("https://data.cms.gov/provider-data/topics/nursing-homes", "dataset and reporting-context boundary"), source("https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/", "inspection-record meaning and limits"), source("https://www.medicare.gov/providers-services/original-medicare/nursing-homes/choosing", "visit and comparison boundary")],
 "body": '''<div style="color:var(--teal)">A public field earns its place in a decision only when it changes what a family checks in person.</div>
<section class="direct-answer"><h2>Translate one dataset field into one observation, not a facility verdict</h2><p>A family can open a provider-data file or a Care Compare profile and immediately see numbers, dates, and labels that feel decisive. They are valuable starting points, but they are not a live report about a particular resident or a particular shift. The productive move is to write the field exactly as displayed, keep its reporting date beside it, and ask what visit observation could either add context or show that a further question is needed.</p><p>For example, a staffing-related field should not become “there will be enough help for my parent tonight.” It can become: “During the hours we would normally visit, how are call requests assigned and who can explain a delay?” An inspection-related field should not become “this home is unsafe.” It can become: “I saw this dated public finding; what process is used now, and what can a visitor reasonably see or ask about it?” The distinction prevents a population-level public measure from being presented as a promise about one person.</p></section>
<section class="type-element"><h2>Build a field-to-observation card before each facility tour</h2><table class="data"><thead><tr><th>Keep from the public record</th><th>Turn it into</th><th>Record after the visit</th></tr></thead><tbody><tr><td>Field name, facility identifier, and reporting date</td><td>A neutral question about the current process</td><td>Who answered, the date, and any source offered</td></tr><tr><td>An inspection topic or quality-measure label</td><td>One observable part of the routine relevant to the topic</td><td>What was actually observed, without guessing about private care</td></tr><tr><td>A comparison concern</td><td>The same question for both homes</td><td>Whether the answers are comparable or need follow-up</td></tr></tbody></table><p>The card is intentionally modest. It asks a family to separate the source from its interpretation and the interpretation from a conclusion. CMS publishes nursing-home data for public use, while Medicare explains that inspection results reflect inspections and complaints over time. Those facts make a public record useful context; they do not settle bed availability, resident fit, current staffing on a named shift, or clinical suitability.</p></section>
<section class="scenario-block"><h2>Scenario: a data field changes the second tour itinerary</h2><p>Two facilities remain after a hospital discharge planner gives a family names and addresses. A public profile leads the family to want clarity about a care-process topic at one home. Rather than arriving with an accusation, the family writes the field name and date on its card. It asks the same opening question at both homes: “What is the current process for this topic, who can explain it, and what should a family understand during a visit?”</p><p>At the first home, the answer identifies a role, a routine, and a way to ask a follow-up question. At the second, the answer is broad reassurance and no one can identify the current owner of the process. Neither answer erases or proves anything in the public record. The result is a better comparison note: one home supplied a traceable explanation and one left a question open. The family can then decide whether to seek clarification, arrange a second visit, or compare another factor that matters more for the resident.</p></section>
<section class="trust-panel"><h2>What provider data cannot supply for a resident arriving this week</h2><p>Provider data cannot supply a personal care plan, a guarantee about a medication schedule, an answer about a room, or a prediction of how a resident will respond to the setting. It also cannot show every feature of family communication or every detail of a particular shift. Medicare recommends using available comparison information and visiting facilities under consideration. The visit is not a substitute for public data; it is the place to test whether the family can obtain a current, specific explanation.</p><p>Do not turn a field into a request for another resident’s information. A useful tour question asks about the home’s process, ownership, and communication. If the person answering cannot connect a question to a current process, leave that gap visible in the comparison note rather than filling it with a positive or negative assumption.</p></section>
<section><h2>Official source notes for the field-to-tour conversion</h2><p>Use the <a href="https://data.cms.gov/provider-data/topics/nursing-homes">CMS Provider Data Catalog</a> to identify public nursing-home data and its reporting context. Read <a href="https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/">Medicare’s health-inspection explanation</a> before treating an inspection field as a present-tense conclusion. For the visit itself, use <a href="https://www.medicare.gov/providers-services/original-medicare/nursing-homes/choosing">Medicare’s choosing-a-nursing-home guidance</a>. These sources support a method for asking better questions; none determines the appropriate facility for an individual.</p></section>
<section><h2>Correction path when a public field and a tour answer do not align</h2><p>Keep both records. Save the public URL, the facility identifier, and the displayed date; then write the name or role of the person who answered, the date of the conversation, and the follow-up source they offered. Ask which statement concerns the historical record and which describes the current process. If the distinction remains unclear, pause the inference rather than choosing the answer that is easiest to hear. A comparison note that says “needs dated follow-up” is a complete and responsible result.</p><a class="btn btn-primary" href="/compare.html">Open a dated comparison worksheet</a></section>'''
},
118: {
 "title": "Deficiency Pattern Definition: scope severity and survey reading guide",
 "subtitle": "Deficiency pattern definition for scope severity, survey findings, and a nursing home record that families can read carefully.",
 "excerpt": "Learn what a cited deficiency’s scope language can and cannot mean before using it in a facility comparison.",
 "variation": "phase6ak-editorial-deficiency-scope-lexicon",
 "contract": {"reader_job":"read scope and severity language without converting it into a diagnosis","decision_moment":"a family sees isolated, pattern, widespread, or severity wording in a survey record","answer_claim":"scope words describe the cited survey finding and require dated context before a current-care inference","evidence_plan":"CMS enforcement scope explanation, Medicare inspection guidance, CMS Provider Data Catalog","non_overlap_claim":"deficiency vocabulary guide rather than correction-plan timeline or fine-date comparison","structure_reason":"term-boundary lexicon followed by a record-reading case"},
 "sources": [source("https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement", "scope and severity enforcement context"), source("https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/", "citation and inspection context"), source("https://data.cms.gov/provider-data/topics/nursing-homes", "public reporting context")],
 "body": '''<div style="color:var(--clay)">Scope words describe a cited finding; they do not narrate every resident’s present experience.</div>
<section class="direct-answer"><h2>Read a deficiency pattern as a survey term with a date and subject</h2><p>Words such as isolated, pattern, widespread, scope, and severity can look like a simple safety scale. They are not a shortcut to a conclusion about a particular family member’s future care. CMS explains that a survey agency assigns scope and severity levels to each cited deficiency; scope concerns how many residents were affected by that cited deficiency. The first family task is therefore to identify the exact survey date, the cited subject, the wording shown in the official record, and whether any later public record is present.</p><p>That boundary matters because one survey term does not answer every question a family has during a placement search. It does not establish that the same practice continues today, describe a prospective resident’s personal risk, or rank two homes by itself. It does identify a topic that may deserve a clear, dated facility explanation. Reading the term carefully is more respectful than either ignoring it or treating it as proof of present conditions.</p></section>
<section class="type-element"><h2>Use a four-term lexicon before writing a comparison note</h2><dl class="data"><dt><strong>Citation</strong></dt><dd>A finding that the inspection team says did not meet a federal standard; keep the cited topic and survey date attached.</dd><dt><strong>Scope</strong></dt><dd>The survey agency’s level for how many residents were affected by the cited deficiency, such as isolated, pattern, or widespread; it is not a census of all current residents.</dd><dt><strong>Severity</strong></dt><dd>The level assigned to that finding in the survey and enforcement process; it should not be translated into a private clinical prediction.</dd><dt><strong>Later record</strong></dt><dd>A later survey, revisit, public update, or facility explanation that may add context but must be checked for whether it concerns the same subject.</dd></dl><p>Put the exact term in the note, not a stronger paraphrase. “The record uses pattern for this cited finding” is a traceable statement. “The facility has a pattern of poor care” adds a broad conclusion that the specific survey language may not support. This vocabulary discipline makes it possible to compare questions across homes without turning technical terminology into a verdict.</p></section>
<section class="scenario-block"><h2>Scenario: two scope labels appear on a shortlisting call</h2><p>A family sees a scope label on one home’s public inspection information and a different label on another home’s information. The records are from different dates and concern different subjects. Instead of ranking the labels, the family makes two separate rows: date, cited subject, term used, and the question that follows. On the calls, it asks each home which current process applies to that topic, who is responsible for it, and whether a visitor can understand the process without receiving private resident information.</p><p>The first home identifies a current routine and a person who can give a follow-up explanation. The other says only that “the survey is old.” The family records that response as an unanswered current-process question. It does not label either home compliant or noncompliant from the call. The public term and the present answer have different jobs: one identifies a historically cited issue, and the other either supplies or fails to supply a current explanation.</p></section>
<section class="trust-panel"><h2>What a scope or severity label cannot tell you today</h2><p>A label cannot tell a family whether a bed is suitable, whether a resident’s condition can be managed, whether the same staff are on duty, or whether a concern is urgent. It cannot replace a visit, a clinical discussion, or official help when a resident may be in immediate danger. Medicare explains that health-inspection information includes citations based on inspections and other inspection types over time. That context is precisely why an isolated phrase should be retained with its date and topic.</p><p>It is also important not to demand that staff adjudicate the public record in a hallway conversation. Ask for the current process and the appropriate person to explain it. A careful reader allows “unknown” to remain unknown until an appropriate source can answer it.</p></section>
<section><h2>Official source notes for deficiency pattern definitions</h2><p>CMS’s <a href="https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement">nursing-home enforcement page</a> describes scope levels and the survey-and-enforcement setting. Medicare’s <a href="https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/">inspection resource</a> explains citations and public inspection context. The <a href="https://data.cms.gov/provider-data/topics/nursing-homes">CMS Provider Data Catalog</a> is useful for locating the public record. These sources define the record environment, not a personal placement recommendation.</p></section>
<section><h2>Correction path when the term is unclear or the record conflicts</h2><p>Copy the term exactly, retain the source URL and date, and ask for the cited subject rather than guessing from a headline. If two sources appear to describe the same issue differently, write both dates and identify whether either is a later event, a dispute, or a separate inspection. Ask the facility for the current process, not for a promise that the historical record is wrong. If that distinction cannot be made, pause the comparison row and seek the official source or appropriate state assistance.</p><a class="btn btn-primary" href="/methodology.html">Read the Caregos record-reading method</a></section>'''
},
113: {
 "title": "Facility Distance Tradeoff: family visits and care coordination guide",
 "subtitle": "Facility distance tradeoff for family visits, care coordination, nursing home choice, and a realistic weekly travel plan.",
 "excerpt": "Compare travel burden with visit reliability and care coordination without mistaking a nearby address for resident fit.",
 "variation": "phase6ak-editorial-distance-visit-capacity-map",
 "contract": {"reader_job":"weigh realistic visit capacity against other placement factors","decision_moment":"two viable homes differ materially in travel time","answer_claim":"distance should be assessed as a repeatable visit-and-coordination capacity, not a mileage preference","evidence_plan":"Medicare choosing guidance, Care Compare context, resident-rights quality-of-care context","non_overlap_claim":"family travel capacity rather than rating, inspection, or payment comparison","structure_reason":"weekly visit-capacity map with an exception-focused decision ledger"},
 "sources": [source("https://www.medicare.gov/providers-services/original-medicare/nursing-homes/choosing", "facility visits and comparison guidance"), source("https://www.medicare.gov/care-compare/?providerType=NursingHome&redirect=true", "location-based provider comparison context"), source("https://www.cms.gov/about-cms/what-we-do/nursing-homes/patients-caregivers/rights-quality-care", "resident and family quality-of-care context")],
 "body": '''<div style="color:var(--ink-soft)">A closer address matters only if it creates visits and coordination the family can actually sustain.</div>
<section class="direct-answer"><h2>Measure distance as repeatable family access, not as a map pin</h2><p>When two nursing homes look possible, the shorter route can feel like an automatic winner. Distance can be deeply important: it may determine whether a relative can visit after work, join a care conversation, notice a change in routine, or arrive when a resident needs familiar support. But a nearby address is not the same thing as a workable placement. Travel time changes by hour, transportation, weather, parking, mobility, and the family member who will actually make the trips.</p><p>Instead of asking only which home is closer, ask what visit pattern is realistic for the next month. Who can go on weekday evenings, who can go on weekends, and who can answer when the primary visitor cannot? Then keep those answers beside other non-distance questions: whether the facility can discuss the person’s care needs, whether the family can communicate with the relevant team, and whether the environment feels appropriate after a visit. This turns distance into one transparent criterion rather than an invisible tie-breaker.</p></section>
<section class="type-element"><h2>Create a weekly visit-capacity map before choosing the nearer home</h2><table class="data"><thead><tr><th>Question</th><th>Home A</th><th>Home B</th></tr></thead><tbody><tr><td>Realistic door-to-door time at likely visit hours</td><td>Write a tested estimate</td><td>Write a tested estimate</td></tr><tr><td>Named backup visitor or remote check-in plan</td><td>List role, not a promise</td><td>List role, not a promise</td></tr><tr><td>Ability to attend a care discussion when needed</td><td>Note obstacles and contact path</td><td>Note obstacles and contact path</td></tr><tr><td>Resident-specific reason this travel burden matters</td><td>Keep it tied to the person</td><td>Keep it tied to the person</td></tr></tbody></table><p>The point of the map is not to award points for mileage. It makes an assumption visible. A family that expects three short visits each week may discover that the route permits one. Another family may find that a farther home is still reachable because multiple relatives share trips. Either result is better than choosing a facility on a distance estimate that no one has tested.</p></section>
<section class="scenario-block"><h2>Scenario: the closer home leaves no workable evening visit window</h2><p>A daughter can visit after work twice a week, while a sibling can help only on Saturday. Home A is nearer on a map, but the door-to-door route during the available evening window takes longer than assumed and the visiting plan depends on a parking arrangement that is unreliable. Home B is farther, yet the siblings can coordinate one longer weekday visit and a regular weekend visit without losing the ability to contact the care team.</p><p>The family does not conclude that Home B is better because it is farther or that Home A is worse because the route is inconvenient. It writes the actual pattern: expected visits, backup contact, travel constraints, and the resident’s own preferences. It then asks both homes how families schedule conversations with the appropriate staff and whether a visitor can understand how to raise a routine question. The resulting choice may favor either home, but the reason is a usable support plan rather than an abstract distance preference.</p></section>
<section class="trust-panel"><h2>What a distance calculation cannot answer about resident fit</h2><p>Distance cannot tell a family whether a home can meet a person’s care needs, whether a bed is available, whether the setting feels respectful, or whether a care plan will be appropriate. It also cannot establish that frequent family visits will substitute for the facility’s responsibility to provide care. Medicare advises people to use comparison information and visit facilities they are considering; a visit lets a family understand care and life at the facility and ask questions of residents, families, and staff.</p><p>A travel plan should not pressure a resident to select a home solely for another person’s convenience. Include the resident’s stated preferences when they can be expressed, and keep care, safety, payment, and availability questions separate. The map is a coordination tool, not a moral scorecard for relatives.</p></section>
<section><h2>Official source notes for a distance-and-visits comparison</h2><p>Medicare’s <a href="https://www.medicare.gov/providers-services/original-medicare/nursing-homes/choosing">choosing-a-nursing-home guidance</a> recommends comparing information and visiting homes under consideration. <a href="https://www.medicare.gov/care-compare/?providerType=NursingHome&redirect=true">Care Compare</a> provides location-based access to Medicare-certified provider comparisons. CMS’s <a href="https://www.cms.gov/about-cms/what-we-do/nursing-homes/patients-caregivers/rights-quality-care">resident rights and quality-of-care material</a> provides broader context for the resident-centered boundary. None of these sources can select a home for a specific family.</p></section>
<section><h2>Correction path when the family travel plan breaks down</h2><p>Do not hide the change. Update the map with the actual travel time, identify which visit or care-discussion commitment is no longer realistic, and ask whether another relative or communication route can reliably cover it. If the original choice depended on a visit pattern that is not sustainable, reconsider it alongside the resident’s needs and other placement facts. A revised plan is not a failure; it is better evidence than continuing a schedule that exists only on paper.</p><a class="btn btn-primary" href="/facility.html">Compare facility notes with a visit-capacity column</a></section>'''
},
107: {
 "title": "Fine Date Vs Survey Date: civil money penalty timeline guide",
 "subtitle": "Fine date vs survey date for enforcement remedy, survey findings, and a nursing home timeline families can verify.",
 "excerpt": "Separate the date of a cited survey finding from the date of an enforcement remedy before comparing facilities.",
 "variation": "phase6ak-editorial-enforcement-date-lane",
 "contract": {"reader_job":"separate a survey event from an enforcement action in public records","decision_moment":"a civil money penalty date appears next to a facility’s survey information","answer_claim":"a fine date and survey date can have different procedural meanings and must not be used interchangeably","evidence_plan":"CMS enforcement process, Medicare inspection and citation context, CMS Provider Data Catalog","non_overlap_claim":"enforcement date reconciliation rather than correction-plan follow-up or deficiency definitions","structure_reason":"two-lane event/remedy timeline with a dated comparison scenario"},
 "sources": [source("https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement", "remedies and survey-enforcement process"), source("https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/", "citations, penalties, and public inspection context"), source("https://data.cms.gov/provider-data/topics/nursing-homes", "provider-data reference boundary")],
 "body": '''<div style="color:var(--teal)">A fine date is an enforcement event; a survey date is an inspection event. Put them on separate lines.</div>
<section class="direct-answer"><h2>Keep the survey finding and enforcement remedy in different date lanes</h2><p>A public record may show a civil money penalty or another enforcement action near information about a nursing-home survey. It is tempting to read the most recent date as the date of the care event, or to treat the dollar amount as a direct measure of what a future resident will experience. CMS describes enforcement actions as remedies that may be imposed when a nursing home does not meet federal requirements, while state survey agencies conduct surveys that determine compliance. Those related steps do not necessarily occur on the same day or answer the same question.</p><p>Start a two-lane timeline. In the first lane, record the survey or inspection date, the cited topic, and any scope or severity wording shown. In the second, record the enforcement date, remedy type, and source page. A later remedy can reflect a process following a survey; it is not automatically a newer observation of the facility. A family can then ask a better current question: what process applies now to the historical topic, who owns it, and what later public context exists?</p></section>
<section class="type-element"><h2>Use the event-remedy timeline instead of a single alarming date</h2><ol class="data"><li><strong>Survey lane:</strong> copy the survey date and the specific cited subject without replacing it with a general accusation.</li><li><strong>Remedy lane:</strong> identify the remedy, such as a civil money penalty, and its listed date or action reference.</li><li><strong>Link lane:</strong> note only the connection shown by the official record; do not assume every action and survey entry are one event.</li><li><strong>Current lane:</strong> ask the facility for the present process and the appropriate follow-up source, keeping the answer separate from the historical record.</li></ol><p>This layout helps prevent two opposite errors. One is to dismiss a survey finding because a remedy appears later. The other is to describe a later enforcement date as proof that the same condition happened later. Both blur a record that should remain chronological. A family needs a dated explanation, not a simplified headline.</p></section>
<section class="scenario-block"><h2>Scenario: a recent fine date is mistaken for a recent survey</h2><p>During a rapid placement search, a relative finds a penalty date that looks recent and concludes that it describes a current inspection. Another relative finds an earlier survey record. They make two lanes before calling the facility. The call begins with a factual question: “We saw this dated survey record and this dated enforcement record. Can you identify the current process for the survey topic and the right source for any later public context?”</p><p>The admissions contact may be able to identify the role that owns the current process, but may not be the final authority on a federal enforcement timeline. The family records the answer and seeks the cited public material rather than demanding an immediate legal interpretation. The comparison note can honestly say whether the dates were reconciled, whether a current process was identified, and whether an official follow-up is still needed. It should not say that a penalty proves current harm or that a facility explanation erases the public record.</p></section>
<section class="trust-panel"><h2>What a civil money penalty date cannot establish today</h2><p>A remedy date cannot establish the present condition of a unit, the safety of a prospective resident, the availability of a bed, or the clinical appropriateness of a placement. Medicare notes that penalties may be imposed for serious citations or citations not corrected for a long time, and that public inspection information includes several kinds of inspection. Those facts show why the date needs process context. They do not let a general reader resolve compliance, dispute status, or a resident-specific risk.</p><p>If a family believes there is an immediate care or safety concern, a historical-record worksheet is not the right response. Use the appropriate emergency or state channels. This article’s narrow purpose is to prevent date confusion during a comparison, not to provide legal advice or complaint handling.</p></section>
<section><h2>Official source notes for fine dates and survey dates</h2><p>CMS explains remedies and the <a href="https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement">nursing-home enforcement process</a>. Medicare’s <a href="https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/">health-inspection resource</a> explains citations, complaints, and penalties in public comparison context. The <a href="https://data.cms.gov/provider-data/topics/nursing-homes">CMS Provider Data Catalog</a> is a reference point for public nursing-home data. Use these records to preserve chronology, not to make a present-tense judgment.</p></section>
<section><h2>Correction path when the dates appear to conflict</h2><p>Save both URLs and write the date labels exactly as the sources display them. Ask whether the sources identify a survey, remedy, revisit, dispute, or another event, and avoid merging them until the record itself connects them. If a facility answer is broad, ask for the role responsible for the current process and the next public or official source. Keep an unresolved row as unresolved. The correct response to a timeline gap is a follow-up request, not a more confident inference.</p><a class="btn btn-primary" href="/compare.html">Add separate survey and remedy lanes to a comparison note</a></section>'''
},
122: {
 "title": "Medication Review Question: pharmacy review and SNF transition guide",
 "subtitle": "Medication review question for SNF transition, medication list, follow-up care, and a family update conversation.",
 "excerpt": "Prepare a medication-review conversation for a transition without asking a public measure to replace the resident’s clinical plan.",
 "variation": "phase6ak-editorial-medication-handoff-dialogue",
 "contract": {"reader_job":"prepare a safe medication-handoff conversation during a facility transition","decision_moment":"a family is choosing or entering an SNF after another care setting","answer_claim":"a public medication-review measure should lead to questions about reconciliation, responsible roles, and escalation—not a medication decision","evidence_plan":"CMS quality-measure definition, CMS quality-measure context, Medicare nursing-home selection guidance","non_overlap_claim":"transition medication dialogue rather than inspection, rating, or coverage article","structure_reason":"role-based handoff dialogue and missing-information escalation card"},
 "sources": [source("https://data.cms.gov/provider-data/topics/nursing-homes/quality-measures", "medication review and follow-up measure meaning"), source("https://www.cms.gov/medicare/quality/nursing-home-improvement/quality-measures", "quality-measure reporting context"), source("https://www.medicare.gov/providers-services/original-medicare/nursing-homes/choosing", "facility-choice and visit boundary")],
 "body": '''<div style="color:var(--clay)">A medication-review measure can prompt a safer handoff question, but it cannot prescribe for one resident.</div>
<section class="direct-answer"><h2>Ask who reconciles the medication list, who follows up, and how the family is informed</h2><p>Medication questions become urgent when someone moves from a hospital, home, rehabilitation stay, or another facility into a skilled-nursing setting. A family may see a public quality measure about medication review and assume it answers whether every medicine will be correct on arrival. It does not. CMS describes a measure about SNF stays in which medications were reviewed at admission and during the stay and received follow-up when issues were identified. That is useful context for a process conversation, not an individual clinical determination.</p><p>The practical question is role-based: who receives the current list, who performs or coordinates the review under the facility’s process, how are questions routed to the appropriate clinician, and how will a family learn what information is still missing? No article can tell a family to start, stop, substitute, or change a medication. It can help the family preserve the source of the list, the person responsible for each next question, and the point at which a clinician must be contacted.</p></section>
<section class="type-element"><h2>Use a handoff dialogue card rather than a medication checklist</h2><table class="data"><thead><tr><th>Ask</th><th>Why it is a process question</th><th>Keep in the family note</th></tr></thead><tbody><tr><td>What current medication list did the receiving team receive?</td><td>It identifies the document without declaring it complete.</td><td>Source, date, and any missing fields named by staff.</td></tr><tr><td>Which role coordinates review and follow-up when an issue is found?</td><td>It identifies an escalation path, not a treatment choice.</td><td>Role, callback route, and expected next contact.</td></tr><tr><td>How should the family raise a discrepancy or concern?</td><td>It separates routine communication from urgent clinical advice.</td><td>Who to contact and what information to have ready.</td></tr></tbody></table><p>A dialogue card should contain only information the family can accurately provide: medication list source, dates, recent setting, named questions, and contact routes. It should not be used to record unnecessary private details about other residents or to pressure a staff member into making a clinical decision outside the appropriate review process. If the resident has an urgent symptom or immediate safety concern, use the facility’s urgent clinical route or emergency help rather than waiting for a comparison worksheet.</p></section>
<section class="scenario-block"><h2>Scenario: a discharge list and a facility intake list do not match</h2><p>A son brings a discharge packet to an SNF admission and notices that a medication name on the family’s copy does not appear in the intake conversation. He does not decide that the medication was omitted or instruct anyone to add it. He asks which list the receiving team is using, whether the discrepancy has been routed to the appropriate clinical reviewer, and how the family will receive a follow-up answer. He records the time, the role of the person receiving the question, and the next contact point.</p><p>That response is more useful than arguing from a public percentage. The quality measure can explain why medication review and follow-up are important around transitions, but it cannot settle the discrepancy. If the team identifies that a clinician must review the record, the family’s job is to preserve the question and use the stated escalation route. If an answer remains unclear, the next step is to ask the responsible clinical or facility contact for the current status, not to rely on an internet summary.</p></section>
<section class="trust-panel"><h2>What this medication-review question cannot decide for one person</h2><p>It cannot tell a family whether a medication is appropriate, whether a dose should change, whether an interaction exists, or whether a resident should be admitted. It cannot replace the prescriber, pharmacist, nurse, or other clinician responsible for the resident’s care. CMS’s public measure reports a process across SNF stays, not a guarantee about a particular handoff. A high or low public figure should therefore be read as a reason to ask about process and follow-up, not as a medication instruction.</p><p>The same boundary protects the resident. Families can be active participants in communication without being asked to make a clinical judgment from incomplete records. Keep questions specific and time-stamped, and ask which person or team owns the next clinically appropriate answer.</p></section>
<section><h2>Official source notes for medication review and follow-up</h2><p>The <a href="https://data.cms.gov/provider-data/topics/nursing-homes/quality-measures">CMS Provider Data Catalog quality-measures page</a> describes the SNF medication-review and follow-up measure. CMS’s <a href="https://www.cms.gov/medicare/quality/nursing-home-improvement/quality-measures">quality-measures resource</a> provides reporting context and technical materials. Medicare’s <a href="https://www.medicare.gov/providers-services/original-medicare/nursing-homes/choosing">nursing-home selection guidance</a> frames the wider facility-comparison boundary. These official sources do not replace resident-specific clinical advice.</p></section>
<section><h2>Correction path when medication information is missing or inconsistent</h2><p>Do not repair the list yourself. Preserve the source documents, write what appears inconsistent, and ask the receiving team which role will review it and when the family should expect an answer. If someone advises a change, request that the appropriate clinical owner confirm it through the facility’s process. If the concern is urgent, follow the facility’s urgent instructions or seek emergency help. A documented escalation is safer than a confident guess.</p><a class="btn btn-primary" href="/facility.html">Keep a transition conversation note with the facility comparison</a></section>'''
}
}


def main():
    stamp = datetime.now(timezone.utc).isoformat()
    for record_id, article in ARTICLES.items():
        path = next(POSTS.glob(f"{record_id}-phase6ak-*.json"))
        post = json.loads(path.read_text(encoding="utf-8-sig"))
        post.update({
            "title": article["title"], "subtitle": article["subtitle"],
            "excerpt": article["excerpt"], "body_html": article["body"],
            "meta_title": article["title"][:58], "meta_description": article["excerpt"],
            "quality_score": 95, "template_variation": article["variation"],
            "review_status": "needs_human_review", "editorial_contract": article["contract"],
            "research_evidence": {"fact_traceability_pass": True, "sources": article["sources"],
                                  "source_interpretation": article["contract"]["non_overlap_claim"]},
            "rewrite_evidence": {"rewritten_by": "codex-caregos-batch-a", "rewritten_at": stamp,
                                 "method": "independent official-source editorial rewrite; held pending human review"},
        })
        post["external_source"] = {"label": "Official nursing home source context", "url": article["sources"][0]["url"]}
        path.write_text(json.dumps(post, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"rewritten-held {record_id} {path.name}")


if __name__ == "__main__":
    main()
