#!/usr/bin/env python3
"""Curated held-draft rewrite for record 106; it never approves or publishes."""
import json
from pathlib import Path

path = next(Path('content/posts').glob('106-*.json'))
post = json.loads(path.read_text(encoding='utf-8'))
if post.get('review_status') not in (None, 'needs_human_review'):
    raise SystemExit('record is not held for review')

body = '''<div style="color:var(--teal)">Read the record in time order before treating it as a verdict.</div>
<section class="direct-answer"><h2>Start with the event and date, not the most alarming label</h2><p>A complaint-survey entry can make a family feel that a decision must be made immediately. The record is useful, but it is not a bedside report and it is not a diagnosis of current care. The first task is to identify what the entry is describing: a standard survey, a complaint investigation, a facility-reported incident inspection, or a later enforcement action. Then write down the event date, the public posting or processing date, the cited subject, and the source page. Those dates often answer different questions. A newer page can describe an older event, and a later action can be connected to a different part of the record.</p><p>This reading order gives a family something more useful than a yes-or-no rating. It turns a public entry into a question that can be checked during a call or tour. It also prevents a common mistake: assuming that a complaint entry means every concern was substantiated, that no corrective action occurred, or that the same condition exists today. Public information can identify a reason to ask; it cannot replace a current answer from the facility or a resident-specific care discussion.</p></section>
<section class="trust-panel"><h2>Use a four-step chronology card before comparing facilities</h2><ol class="type-element"><li><strong>Identify the event:</strong> Was it a standard survey, complaint investigation, incident inspection, or enforcement record?</li><li><strong>Read the cited concern:</strong> Record the subject in neutral words rather than rewriting it as a conclusion.</li><li><strong>Add context:</strong> Note any scope, severity, revisit, dispute, or date information shown by the public source.</li><li><strong>Convert it to a current question:</strong> Ask what process exists now, who can explain it, and what a family can observe or document on a visit.</li></ol><p>Keep the card to facts and unanswered questions. Do not infer that a family member was harmed, that a resident is unsafe, or that the facility has not changed. If the record is unclear, the useful outcome is “needs clarification,” not a forced ranking. This is especially important when a discharge timeline is tight, because urgency can make an old or incomplete record feel like a complete answer.</p></section>
<section class="scenario-block"><h2>Scenario: a complaint entry appears beside a recent standard survey</h2><p>Consider two homes on a shortlist. One has a complaint-related entry that catches the family's attention; the other has a different standard-survey history. The family first records the dates and the type of each entry. On the call, they ask each home to explain the current process related to the public concern, who owns follow-up, and what a visitor may ask or observe without seeking another resident's private information. The family does not ask staff to prove that the record is wrong, and it does not describe the entry as proof that current care is poor. It asks for a dated, answerable explanation.</p><p>That scenario produces comparable information. If one home gives a general reassurance without identifying a process, the family can note that answer rather than inventing a conclusion. If another home gives a current policy but the public dates still do not align, the next step is to ask for the relevant source or to pause the comparison until the chronology is clearer. The public record and the facility answer are both inputs; neither should be presented as the whole story.</p></section>
<section><h2>Turn the record into a respectful tour question</h2><p>A useful question is specific, current, and non-accusatory: “I saw a public inspection entry dated [date] about [subject]. What is the current process, who reviews it, and what should a family understand before making a decision?” A weak question demands private resident details or assumes fault. The goal is to learn how the home explains a process, communicates with families, and responds when a concern is raised. Record who answered and whether a follow-up source was offered.</p><p>This article does not teach someone how to file a complaint or decide whether a complaint will be substantiated. If a person has an immediate concern about care or safety, the appropriate state and emergency channels are separate from a comparison worksheet. The worksheet is for interpreting already public information without overstating it.</p></section>
<section><h2>What a public inspection record cannot tell you today</h2><p>It cannot tell you the resident's current experience, whether a particular practice has changed, or which facility is right for a family. It cannot replace a care-plan conversation, a visit, or official assistance for an urgent concern. Medicare explains that inspection information is one part of nursing-home comparison and that inspectors review many aspects of life and care. Read that context before treating an isolated label as a final answer.</p></section>
<section><h2>Official source records for the chronology card</h2><p>Use <a href="https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/">Medicare's health-inspection explanation</a> to distinguish inspection context, complaints, citations, and public reporting. Use <a href="https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement">CMS nursing-home enforcement information</a> for enforcement-process context. Use the <a href="https://data.cms.gov/provider-data/topics/nursing-homes">CMS Provider Data Catalog</a> to confirm data-release context where applicable. These official sources support a record-reading method; they do not establish a present condition at a named facility.</p></section>
<section><h2>Correction path when dates or claims do not reconcile</h2><p>Write the conflict down. Ask for the event date, the public-source link, the name of the person explaining the current process, and the next source that can clarify the discrepancy. Do not replace an unknown with an assumption just to finish a shortlist. A dated note that says “unresolved” is a responsible comparison result.</p><a class="btn btn-primary" href="/blog/compare-after-complaint/">Build a neutral facility comparison note</a></section>'''
post.update({
    'title':'Complaint Survey Reading Order: nursing home record chronology guide',
    'subtitle':'Complaint survey reading order for standard survey, complaint investigation, nursing home record, and a neutral current-question workflow.',
    'excerpt':'Read complaint and standard-survey records in chronology before turning them into a tour question or facility comparison note.',
    'body_html':body,
    'template_variation':'phase6ak-editorial-complaint-survey-chronology',
    'review_status':'needs_human_review',
    'editorial_contract':{'reader_job':'read public complaint and survey records in order','decision_moment':'an alarming entry appears before a tour or discharge call','answer_claim':'chronology must precede a comparison conclusion','evidence_plan':'Medicare inspection explanation, CMS enforcement, Provider Data Catalog','non_overlap_claim':'record-reading chronology, not complaint filing or rating comparison','structure_reason':'four-step chronology card and neutral tour-question conversion'},
    'research_evidence':{'fact_traceability_pass':True,'sources':[{'url':'https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/','source_role':'official','used_for':'inspection, complaint, and citation context'},{'url':'https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement','source_role':'official','used_for':'enforcement-process boundary'},{'url':'https://data.cms.gov/provider-data/topics/nursing-homes','source_role':'official','used_for':'public data release context'}],'source_interpretation':'uses public sources to construct a chronology card, not to judge present care'}
})
path.write_text(json.dumps(post,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(path)
