#!/usr/bin/env python3
"""One individually authored, held rewrite for phase6ak record 108."""
import json
from pathlib import Path

path = next(Path('content/posts').glob('108-*.json'))
post = json.loads(path.read_text(encoding='utf-8'))
if post.get('review_status') not in (None, 'needs_human_review'):
    raise SystemExit('record is not held')

body = '''<div style="color:var(--clay)">A plan of correction is an allegation of corrective action, not proof that a concern is gone.</div>
<section class="direct-answer"><h2>Read the plan date, later survey, and current answer as three separate facts</h2><p>Families often see that a nursing home submitted a plan of correction and assume the public record has been closed. A plan of correction is important because it describes what a facility says it will do in response to cited deficiencies. It is not, by itself, a current-care guarantee. The useful follow-up is to place three facts on one timeline: the survey or citation date, the corrective-action completion date stated in the plan, and any later inspection or current explanation that can be checked. Each fact answers a different question.</p><p>This distinction protects both the family and the facility from a careless conclusion. A past finding does not automatically describe today's resident experience. At the same time, a stated completion date does not tell a reader whether a later survey occurred, whether a different concern is involved, or what a current process looks like. The article therefore helps a family prepare a neutral follow-up question rather than decide whether a home is compliant.</p></section>
<section class="trust-panel"><h2>Build a correction follow-up timeline instead of a one-line verdict</h2><ol class="type-element"><li><strong>Finding:</strong> record the public survey date, cited subject, and the source page.</li><li><strong>Plan:</strong> record what the plan says will be changed and its stated completion date.</li><li><strong>Later evidence:</strong> look for a later survey, revisit, or public update without assuming it addresses the same issue.</li><li><strong>Current question:</strong> ask the facility who owns the process now, how it is monitored, and what documentation or observation a family can reasonably request.</li></ol><p>Use neutral language in the note. “The record says a plan was submitted” is different from “the problem was fixed.” If a public record contains a dispute or an incomplete timeline, preserve that uncertainty. The appropriate result may be a paused comparison rather than a forced ranking. A family should avoid asking for another resident's private information or asking a staff member to make a legal conclusion about compliance.</p></section>
<section class="scenario-block"><h2>Scenario: a completion date appears before a later placement decision</h2><p>A discharge planner gives a family two facility names. One public record shows a correction-plan completion date from months earlier. The family writes the citation date and stated completion date, then asks the admissions contact: “What process is in place now for this topic, who reviews it, and is there a later public record we should read?” The answer may be useful, but it is kept separate from the public timeline. If the contact cannot identify the process or date, the family records the gap and continues comparing other facts.</p><p>The scenario does not make the correction plan meaningless. It gives the plan the right role: a starting point for a dated follow-up. The family can also ask the care team whether the resident has needs that make this topic especially important, without assuming that a general inspection record answers a resident-specific question.</p></section>
<section><h2>Use compliance history carefully when comparing two homes</h2><p>Compliance history can help a family decide which questions deserve time, but it should not be converted into a scorecard without context. Different citations, survey cycles, and enforcement paths may not be directly comparable. A better comparison note lists the public source, date, subject, current facility explanation, and unresolved question for each home. That format makes it visible when one answer is evidence-backed and when it is only a reassurance.</p><p>This article does not define every enforcement remedy or advise a family how to challenge a survey result. If there is an urgent care or safety concern, use the appropriate official state or emergency channels rather than relying on a comparison worksheet.</p></section>
<section><h2>What a correction plan cannot establish for a resident today</h2><p>It cannot establish present compliance, care quality, personal safety, eligibility, or the right placement. It cannot replace a visit, a care-plan conversation, or an official response to an urgent concern. It can only show a documented response path that must be read with dates and later evidence.</p></section>
<section><h2>Official source records for correction-plan follow-up</h2><p>CMS explains nursing-home enforcement and the role of plans of correction in its <a href="https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement">nursing-home enforcement information</a>. Medicare's <a href="https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/">health-inspection guidance</a> supplies inspection and citation context. The <a href="https://data.cms.gov/provider-data/topics/nursing-homes">CMS Provider Data Catalog</a> helps a reader check current public-data release context. These sources are used to construct a timeline, not to determine current compliance at a named facility.</p></section>
<section><h2>Correction path when the public timeline is incomplete</h2><p>Write down the missing date or unexplained link. Ask for the relevant public record, the current-process owner, and the next source that can clarify the issue. Do not replace an unknown with a favorable or unfavorable assumption. A family can keep a facility on a shortlist while the answer is unresolved, but it should not describe the plan as proof of correction.</p><a class="btn btn-primary" href="/blog/correction-plan-meaning/">Prepare a correction-plan evidence note</a></section>'''
post.update({'title':'Correction Plan Follow Up: plan of correction and later survey guide','subtitle':'Correction plan follow up for plan of correction, later survey, compliance history, and a dated family evidence note.','excerpt':'Use a correction-plan timeline to separate a cited finding, stated completion date, later evidence, and the current facility question.','body_html':body,'template_variation':'phase6ak-editorial-correction-follow-up-timeline','review_status':'needs_human_review','editorial_contract':{'reader_job':'follow a correction plan without mistaking it for proof','decision_moment':'a public correction-plan record appears during a facility comparison','answer_claim':'plan date, later survey, and current answer are distinct facts','evidence_plan':'CMS enforcement, Medicare inspection context, CMS data catalog','non_overlap_claim':'timeline follow-up rather than complaint reading or deficiency glossary','structure_reason':'four-part correction follow-up timeline'},'research_evidence':{'fact_traceability_pass':True,'sources':[{'url':'https://www.cms.gov/medicare/health-safety-standards/enforcement/nursing-home-enforcement','source_role':'official','used_for':'plan of correction and enforcement context'},{'url':'https://www.medicare.gov/care-compare/resources/nursing-home/health-inspections/','source_role':'official','used_for':'inspection and citation context'},{'url':'https://data.cms.gov/provider-data/topics/nursing-homes','source_role':'official','used_for':'public data context'}],'source_interpretation':'reads a plan as one dated step rather than evidence of present compliance'}})
path.write_text(json.dumps(post,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(path)
